### ISSUE TITLE
Update the prettier peer dependency version

### ISSUE THREAD

**Issue by softwarespot** [npetruzzelli/prettier-config-standard#5]
Current Prettier version I have installed is 2.5.1. 

If Node.js v14.* is used, then it treats this as a warning and so is able to install the dependency. Whereas Node.js v16+ treats this as an error

**Output of Node.js v14.19.0**
```
[verbose] npm WARN prettier-config-standard@4.1.0 requires a peer of prettier@>= 2.0.0 < 2.4.0 but none is installed. You must install peer dependencies yourself.
```

Happy to provide more information if required. Thanks for your support =)

**Comment by MaximeCheramy** [comment]
@softwarespot Please try with `prettier-config-standard@5.0.0` instead of the version 4.1.0.

**Comment by softwarespot** [comment]
Excellent. This solved it. Thanks for your help
